name = input("Wat is uw naam?")
adres = input("Wat is uw adres?")
post = input("Wat is uw postcode?")
woon = input("Wat is uw woonplaats(stad of drop)?")

print("----------------------------------------------------")
print("|  Naam      :", name)
print("|  Adres     :", adres)
print("|  Postcode  :", post)                         
print("|  Woonplaats:", woon)                          
print("----------------------------------------------------")